### ISSUE TITLE
Double rendering body when using body.setSize during update

### ISSUE THREAD

**Issue by fyyyyy** [samme/phaser-plugin-debug-arcade-physics#3]
I use camera scaling, and since arcade bodies do not scale with the camera, i have to update the bodies manually  (via this.body.setSize...) whenever the camera.scale changes. However this will render 2 bodies instead of one with this plugin. When using vanilla game.debug.body(sprite... it works fine however.

![image](https://user-images.githubusercontent.com/3744048/29471857-de21df66-8451-11e7-9368-d704cd92d366.png)

**Comment by samme** [comment]
Could you post an example? <https://codepen.io/pen?template=vyKJvw>

**Comment by fyyyyy** [comment]
Actually i could not replicate this. I must have something else going on with more bodies floating around than i expected. Anyhow, heres the example which works fine.
https://codepen.io/anon/pen/ayqMLP?editors=0010
